# This file was generated by GoReleaser. DO NOT EDIT.
cask "terramate-atlantis-config" do
  name "terramate-atlantis-config"
  desc "Generate Atlantis config for Terramate projects"
  homepage "https://github.com/devops-roast/terramate-atlantis-config"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terramate-atlantis-config"

  on_macos do
    on_intel do
      url "https://github.com/devops-roast/terramate-atlantis-config/releases/download/v#{version}/terramate-atlantis-config_#{version}_darwin_amd64.tar.gz"
      sha256 "6d87cf8a872cc614d33317d8aa06c940c9eeba5f76475a709fba467523fd3846"
    end
    on_arm do
      url "https://github.com/devops-roast/terramate-atlantis-config/releases/download/v#{version}/terramate-atlantis-config_#{version}_darwin_arm64.tar.gz"
      sha256 "beb6205cc13469562890d7ebd236ffd99b6528c6e61a9fb6c6b25877631bdb90"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devops-roast/terramate-atlantis-config/releases/download/v#{version}/terramate-atlantis-config_#{version}_linux_amd64.tar.gz"
      sha256 "93a4466d0b3ca9f681a64d59c3be72f67a78cfc373376e05300dc17e7a37ea79"
    end
    on_arm do
      url "https://github.com/devops-roast/terramate-atlantis-config/releases/download/v#{version}/terramate-atlantis-config_#{version}_linux_arm64.tar.gz"
      sha256 "c5a6db3e65812d2d740122b26bf438635ba848a118fa6630de9ce47d10e818ab"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terramate-atlantis-config"]
    end
  end

  # No zap stanza required
end
